[project]
name = "detective-conan-filter"
version = "0.1.0"
description = "Filters detective conan episodes according to your interests"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.0",
    "pandas>=2.3.0",
    "requests>=2.32.4",
]
